import initScrollSuave from './js/modules/scroll-suave.js';
import initAnimacaoScrollpag from './js/modules/scroll-animacao.js';
import initAccordion from './js/modules/accordion.js';
import initTabNav from './js/modules/tabnav.js';
import initModal from './js/modules/modal.js';
import initToolTip from './js/modules/tooltip.js';
import initDropDownMenu from './js/modules/dropdown-menu.js';
import initMenuMobile from './js/modules/menu-mobile.js';
import initAnimaNumeros from './js/modules/anima-numeros.js';
import initFuncionamento from './js/modules/funcionamento.js';

initScrollSuave();
initAnimacaoScrollpag();
initAccordion();
initTabNav();
initModal();
initToolTip();
initDropDownMenu();
initMenuMobile();
initAnimaNumeros();
initFuncionamento();